// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYXMOFJMcaulqIoBTeHR6nymE1yd4pjD0',
    appId: '1:175229399242:web:ba88e5d337676a5bef0433',
    messagingSenderId: '175229399242',
    projectId: 'raknummallshop-b3ce0',
    authDomain: 'raknummallshop-b3ce0.firebaseapp.com',
    storageBucket: 'raknummallshop-b3ce0.firebasestorage.app',
    measurementId: 'G-48MW481GSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedyFrUzIhAHLrLsx6tDTmnudSZyzhM1I',
    appId: '1:175229399242:android:7f223e08b82fd791ef0433',
    messagingSenderId: '175229399242',
    projectId: 'raknummallshop-b3ce0',
    storageBucket: 'raknummallshop-b3ce0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx0Vyfbyj194hdyCT53oDDiu-KZBw10jY',
    appId: '1:175229399242:ios:cb99c5dc46350ed6ef0433',
    messagingSenderId: '175229399242',
    projectId: 'raknummallshop-b3ce0',
    storageBucket: 'raknummallshop-b3ce0.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx0Vyfbyj194hdyCT53oDDiu-KZBw10jY',
    appId: '1:175229399242:ios:cb99c5dc46350ed6ef0433',
    messagingSenderId: '175229399242',
    projectId: 'raknummallshop-b3ce0',
    storageBucket: 'raknummallshop-b3ce0.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYXMOFJMcaulqIoBTeHR6nymE1yd4pjD0',
    appId: '1:175229399242:web:32c30a6ed4f86ac8ef0433',
    messagingSenderId: '175229399242',
    projectId: 'raknummallshop-b3ce0',
    authDomain: 'raknummallshop-b3ce0.firebaseapp.com',
    storageBucket: 'raknummallshop-b3ce0.firebasestorage.app',
    measurementId: 'G-3DZGZR9EVZ',
  );
}
